export type Draw={drawNo:number;numbers:number[];bonus:number};
export const VERSION='coverage-2.0.0';
function hashSeed(s:string){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed:string){let a=hashSeed(seed);return()=>{a|=0;a=a+0x6D2B79F5|0;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function weights(history:Draw[]){const all=Array(46).fill(1),recent=Array(46).fill(1),last=Array(46).fill(-1);history.forEach((d,i)=>d.numbers.forEach(n=>{all[n]++;last[n]=i;if(i>=history.length-30)recent[n]++}));const gap=last.map((x,n)=>n?history.length-x:0);const z=(a:number[])=>{const v=a.slice(1),m=v.reduce((s,x)=>s+x,0)/45,sd=Math.sqrt(v.reduce((s,x)=>s+(x-m)**2,0)/45)||1;return a.map((x,n)=>n?(x-m)/sd:0)};const [a,b,c]=[z(all),z(recent),z(gap)];return a.map((_,n)=>n?Math.max(.05,1+.25*a[n]+.5*b[n]+.25*c[n]):0)}
function partition(nums:number[],random:()=>number){const out=Array.from({length:5},()=>[] as number[]),sorted=[...nums].sort((a,b)=>a-b);for(let band=0;band<6;band++){const order=[0,1,2,3,4];for(let i=4;i;i--){const j=Math.floor(random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}sorted.slice(band*5,band*5+5).forEach((n,i)=>out[order[i]].push(n))}return out.map(x=>x.sort((a,b)=>a-b))}
export function portfolio(history:Draw[],seed:string,predictive=false){const random=rng(seed),pool=Array.from({length:45},(_,i)=>i+1),chosen:number[]=[];if(!predictive){for(let i=44;i;i--){const j=Math.floor(random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}return partition(pool.slice(0,30),random)}const w=weights(history);while(chosen.length<30){let x=random()*pool.reduce((s,n)=>s+w[n],0),pick=pool.at(-1)!;for(const n of pool){x-=w[n];if(x<=0){pick=n;break}}chosen.push(pick);pool.splice(pool.indexOf(pick),1)}return partition(chosen,random)}
export const match=(a:number[],b:number[])=>a.filter(n=>b.includes(n)).length;
export function prize(ticket:number[],draw:Draw){const n=match(ticket,draw.numbers);if(n===6)return 1;if(n===5&&ticket.includes(draw.bonus))return 2;if(n===5)return 3;if(n===4)return 4;if(n===3)return 5;return null}
function cdf(x:number){const t=1/(1+.2316419*Math.abs(x)),d=.3989423*Math.exp(-x*x/2),p=1-d*t*(.3193815+t*(-.3565638+t*(1.781478+t*(-1.821256+t*1.330274))));return x>=0?p:1-p}
export function evaluate(draws:Draw[],min=50){const diffs:number[]=[],rb:number[]=[],pb:number[]=[];for(let i=min;i<draws.length;i++){const h=draws.slice(0,i),d=draws[i],seed=`eval:${d.drawNo}`,best=(t:number[][])=>Math.max(...t.map(x=>match(x,d.numbers)));const r=best(portfolio(h,seed)),p=best(portfolio(h,seed,true));rb.push(r);pb.push(p);diffs.push(p-r)}const n=diffs.length,mean=n?diffs.reduce((s,x)=>s+x,0)/n:0,v=n>1?diffs.reduce((s,x)=>s+(x-mean)**2,0)/(n-1):0,se=Math.sqrt(v/n)||0,margin=1.96*se,pv=se?2*(1-cdf(Math.abs(mean/se))):1,ok=n>0&&pv<.05&&mean-margin>0;return{evaluated:n,randomAverage:n?rb.reduce((s,x)=>s+x,0)/n:0,predictiveAverage:n?pb.reduce((s,x)=>s+x,0)/n:0,meanDifference:mean,ciLow:mean-margin,ciHigh:mean+margin,pValue:pv,recommended:ok?'predictiveCoverage':'randomCoverage',reason:ok?'예측 커버리지가 무작위 기준선보다 유의하게 우수':'유의한 개선 증거가 없어 무작위 커버리지 사용'}}

