import './styles.css'
import './spacing.css'
import {supabase,configured} from './supabase.js'

const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let session=null,current=null
const fmt=n=>(n||0).toLocaleString('ko-KR')
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function balls(nums,i){return `<div class="pick"><em>${i+1}</em>${nums.map(n=>`<span class="ball">${n}</span>`).join('')}</div>`}
function shell(){document.querySelector('#app').innerHTML=`<header><h1>LottoLab <small>CLOUD 2.0</small></h1><span id="status" class="status">연결 확인</span></header><nav><button class="active" data-page="pick">추천</button><button data-page="records">기록</button><button data-page="budget">예산</button><button data-page="settings">설정</button></nav><main>
<section id="pick" class="page active"><div class="hero card"><div><span class="label">대상 회차</span><strong id="target">—</strong></div><div><span class="label">이번 회차 생성</span><strong id="attempts">0/3</strong></div></div><div class="card"><h2>분산형 자동 조합 5게임</h2><p class="muted">30개 숫자를 게임끼리 겹치지 않게 나누고, 생일수·연속수·반복 패턴을 피합니다.</p><button class="primary" id="generate" style="width:100%">5게임 생성</button><div id="picks" class="picks"><p class="muted">아직 생성하지 않았습니다.</p></div><button id="lock" style="width:100%;margin-top:12px" disabled>추첨 전 최종 확정</button><p id="decision" class="muted"></p></div></section>
<section id="records" class="page"><div class="card"><h2>생성 기록</h2><div class="prize-guide" aria-label="당첨 등수 안내"><h3>당첨 등수 안내</h3><div class="prize-row"><span class="rank rank-1">1등</span><span class="prize-condition"><i class="match-dots six"></i><b>6개 일치</b></span><strong>당첨금 변동</strong></div><div class="prize-row"><span class="rank rank-2">2등</span><span class="prize-condition"><i class="match-dots five-bonus"></i><b>5개 + 보너스</b></span><strong>당첨금 변동</strong></div><div class="prize-row"><span class="rank rank-3">3등</span><span class="prize-condition"><i class="match-dots five"></i><b>5개 일치</b></span><strong>1,500,000원</strong></div><div class="prize-row"><span class="rank rank-4">4등</span><span class="prize-condition"><i class="match-dots four"></i><b>4개 일치</b></span><strong>50,000원</strong></div><div class="prize-row"><span class="rank rank-5">5등</span><span class="prize-condition"><i class="match-dots three"></i><b>3개 일치</b></span><strong>5,000원</strong></div></div><div id="recordList"></div></div></section>
<section id="budget" class="page"><div class="card"><h2>이번 달 예산</h2><div id="budgetStats"></div><label>월 한도<input id="monthlyLimit" type="number" step="1000" min="0"></label><button id="saveLimit">한도 저장</button></div><div class="card"><h2>구매 기록</h2><label>대상 회차<input id="purchaseDraw" type="number"></label><label>게임 수<input id="purchaseGames" type="number" value="5"></label><label>지급액<input id="payout" type="number" value="0"></label><button class="primary" id="savePurchase">구매 기록 저장</button><div id="purchaseList"></div></div></section>
<section id="settings" class="page"><div class="card"><h2>계정</h2><p id="account"></p><label>새 로그인 비밀번호<input id="newPassword" type="password" minlength="8" autocomplete="new-password" placeholder="8자 이상"></label><button id="setPassword">비밀번호 설정·변경</button> <button id="signout">로그아웃</button></div><div class="card"><h2>생성 정책</h2><label>회차당 미리보기 횟수<select id="maxAttempts"><option value="1">1회 — 엄격 검증</option><option value="3">3회 — 기본</option></select></label><p class="muted">여러 번 생성해도 최종 5게임의 1등 확률은 변하지 않습니다. 모든 생성 이력은 저장됩니다.</p><button id="saveSettings">설정 저장</button></div></section>
</main><div id="toast"></div>`
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active')})
}
function authScreen(){document.querySelector('#app').innerHTML=`<main style="max-width:460px;padding-top:10vh"><div class="card"><h1>LottoLab <small style="color:#52e0a8;font-size:14px">CLOUD</small></h1><h2 style="margin-top:25px">개인 로그인</h2><p class="muted">이메일을 아이디로 사용합니다.</p><label>이메일<input id="email" type="email" autocomplete="email"></label><label>비밀번호<input id="password" type="password" autocomplete="current-password"></label><button class="primary" id="passwordLogin" style="width:100%">로그인</button><button id="magicLogin" style="width:100%;margin-top:9px">이메일 로그인 링크 받기</button></div></main><div id="toast"></div>`;$('#passwordLogin').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value;if(!email||!password)return toast('이메일과 비밀번호를 입력하세요.');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return toast('이메일 또는 비밀번호를 확인하세요.');await start()};$('#magicLogin').onclick=async()=>{const email=$('#email').value.trim();if(!email)return toast('이메일을 입력하세요.');const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.href.split('#')[0]}});if(error)return toast(error.message);toast('이메일에서 로그인 링크를 확인하세요.')}}
function setupScreen(){document.querySelector('#app').innerHTML=`<main style="max-width:650px;padding-top:8vh"><div class="card"><h1>LottoLab Cloud</h1><h2 style="margin-top:24px">Supabase 연결 필요</h2><p>프로젝트 루트에 <code>.env</code> 파일을 만들고 다음 값을 입력한 뒤 다시 빌드하세요.</p><pre>VITE_SUPABASE_URL=https://프로젝트.supabase.co
VITE_SUPABASE_PUBLISHABLE_KEY=sb_publishable_...</pre><p class="muted">Secret key는 브라우저 파일에 입력하지 마세요.</p></div></main>`}
async function callFunction(name,body={}){const {data,error}=await supabase.functions.invoke(name,{body});if(error){let detail=data?.error||error.message;try{if(error.context instanceof Response){const payload=await error.context.clone().json();detail=payload?.error||payload?.message||detail}}catch{}throw new Error(detail)}if(data?.error)throw new Error(data.error);return data}
async function loadHome(){const state=await callFunction('get-prediction-state');const target=state.targetDraw;$('#target').textContent=`${target}회`;$('#purchaseDraw').value=target;const {data:setting}=await supabase.from('user_settings').select('*').maybeSingle();$('#maxAttempts').value=state.maxAttempts;$('#monthlyLimit').value=setting?.monthly_budget||50000;if(!current&&state.preview){const p=state.preview;current={batchId:p.batchId,tickets:p.tickets};$('#picks').innerHTML=p.tickets.map(balls).join('');$('#decision').textContent=`분산형 자동 조합 · ${p.reason} · ${p.attemptNo}번째 생성`;$('#lock').disabled=false}}
async function loadRecords(){
 const {data,error}=await supabase.from('prediction_batches').select('*,prediction_tickets(*)').order('created_at',{ascending:false}).limit(100);if(error)throw error
 const target=Number($('#target').textContent.replace(/\D/g,'')),forTarget=data.filter(r=>Number(r.target_draw)===target),max=Number($('#maxAttempts').value)||3
 $('#attempts').textContent=`${forTarget.length}/${max}`
 const preview=forTarget.find(r=>r.status==='preview')
 if(!current&&preview){const tickets=[...(preview.prediction_tickets||[])].sort((a,b)=>a.ticket_no-b.ticket_no).map(x=>x.numbers);current={batchId:preview.id,tickets};$('#picks').innerHTML=tickets.map(balls).join('');$('#decision').textContent=`분산형 자동 조합 · ${preview.reason} · ${preview.attempt_no}번째 생성`;$('#lock').disabled=false}else if(!current&&!preview){$('#picks').innerHTML='<p class="muted">아직 생성하지 않았습니다.</p>';$('#decision').textContent='';$('#lock').disabled=true}
 $('#recordList').innerHTML=data.length?data.map(r=>{const tickets=[...(r.prediction_tickets||[])].sort((a,b)=>a.ticket_no-b.ticket_no);return `<div class="row record"><div><strong>${r.target_draw}회 · ${r.attempt_no}번째 생성</strong> <span class="tag">${r.status}</span><br><span class="muted">${r.strategy_used} · ${new Date(r.created_at).toLocaleString()}</span></div><div class="record-picks">${tickets.map((t,i)=>balls(t.numbers,i)).join('')}</div>${r.scored_at?`<span class="${r.best_matches===6?'good':''}">최고 ${r.best_matches}개 일치 ${r.best_prize?`· ${r.best_prize}등`:''}</span>`:''}${['preview','locked'].includes(r.status)?`<button class="danger delete-record" data-id="${r.id}">${r.status==='locked'?'최종 확정본 삭제':'이 생성본 삭제'}</button>`:''}</div>`}).join(''):'<p class="muted">생성 기록이 없습니다.</p>'
 $$('.delete-record').forEach(b=>b.onclick=async()=>{if(!confirm('이 생성본과 번호 5개를 삭제할까요?'))return;b.disabled=true;try{await callFunction('delete-prediction',{batchId:b.dataset.id});current=null;await loadHome();await loadRecords();toast('생성본을 삭제했습니다.')}catch(e){toast(e.message);b.disabled=false}})
}
async function loadBudget(){const month=new Date().toISOString().slice(0,7);const {data}=await supabase.from('purchases').select('*').gte('purchased_at',month+'-01').order('purchased_at',{ascending:false});const cost=(data||[]).reduce((s,x)=>s+x.cost,0),payout=(data||[]).reduce((s,x)=>s+x.payout,0),limit=+$('#monthlyLimit').value||50000;$('#budgetStats').innerHTML=`<div class="metric"><div><strong>${fmt(cost)}원</strong><span>구매</span></div><div><strong>${fmt(Math.max(0,limit-cost))}원</strong><span>남음</span></div><div><strong>${fmt(payout-cost)}원</strong><span>손익</span></div></div>`;$('#purchaseList').innerHTML=(data||[]).map(x=>`<div class="row">${x.target_draw}회 · ${x.games}게임 · ${fmt(x.cost)}원 · 지급 ${fmt(x.payout)}원</div>`).join('')}
async function bind(){
 $('#generate').onclick=async()=>{const b=$('#generate');b.disabled=true;try{current=await callFunction('generate-prediction',{action:'generate'});$('#picks').innerHTML=current.tickets.map(balls).join('');$('#decision').textContent=`${current.strategyLabel} · ${current.reason} · ${current.attemptNo}번째 생성`;$('#attempts').textContent=`${current.attemptNo}/${current.maxAttempts}`;$('#lock').disabled=false;await loadRecords();toast('생성 번호를 기록에 저장했습니다.')}catch(e){toast(e.message)}finally{b.disabled=false}}
 $('#lock').onclick=async()=>{if(!current)return;try{await callFunction('lock-prediction',{batchId:current.batchId});current=null;$('#lock').disabled=true;toast('추첨 전 확정 완료');await Promise.all([loadRecords(),loadHome()])}catch(e){toast(e.message)}}
 $('#saveLimit').onclick=async()=>{const {error}=await supabase.from('user_settings').upsert({user_id:session.user.id,monthly_budget:+$('#monthlyLimit').value},{onConflict:'user_id'});if(error)return toast(error.message);await loadBudget();toast('저장했습니다.')}
 $('#savePurchase').onclick=async()=>{const games=+$('#purchaseGames').value,cost=games*1000,target=+$('#purchaseDraw').value;const {data:locked}=await supabase.from('prediction_batches').select('id').eq('target_draw',target).in('status',['locked','purchased','scored']).maybeSingle();const {error}=await supabase.from('purchases').insert({user_id:session.user.id,target_draw:target,batch_id:locked?.id||null,games,cost,payout:+$('#payout').value,purchased_at:new Date().toISOString().slice(0,10)});if(error)return toast(error.message);await loadBudget();toast(locked?'확정 번호와 구매 기록을 연결했습니다.':'구매 기록을 저장했습니다.')}
 $('#saveSettings').onclick=async()=>{const {error}=await supabase.from('user_settings').upsert({user_id:session.user.id,max_generation_attempts:+$('#maxAttempts').value},{onConflict:'user_id'});if(error)return toast(error.message);await loadHome();toast('정책을 저장했습니다.')}
 $('#setPassword').onclick=async()=>{const password=$('#newPassword').value;if(password.length<8)return toast('비밀번호는 8자 이상 입력하세요.');const {error}=await supabase.auth.updateUser({password});if(error)return toast(error.message);$('#newPassword').value='';toast('비밀번호를 설정했습니다.')}
 $('#signout').onclick=()=>supabase.auth.signOut()
}
async function start(){if(!configured)return setupScreen();const {data}=await supabase.auth.getSession();session=data.session;if(!session)return authScreen();shell();$('#account').textContent=session.user.email;await loadHome();await loadRecords();await loadBudget();await bind();$('#status').textContent='클라우드 연결';if('serviceWorker'in navigator){if(['localhost','127.0.0.1'].includes(location.hostname)){for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister();for(const key of await caches.keys())await caches.delete(key)}else navigator.serviceWorker.register('./sw.js').catch(()=>{})}}
if(configured)supabase.auth.onAuthStateChange((_e,s)=>{if(Boolean(s)!==Boolean(session)){session=s;start().catch(e=>toast(e.message))}})
start().catch(e=>{console.error(e);toast(e.message)})
